### ISSUE TITLE
Version of tensorflow

### ISSUE THREAD

**Issue by MachineryZ** [deworrall92/groupConvolutions#11]
May I ask you which version is your tensorflow?

**Comment by danielewworrall** [comment]
This was using TF 1.3, if I remember correctly

**Comment by MachineryZ** [comment]
I ran the command:python run_mnist.py --combine_train_val True
and I got the error:

Traceback (most recent call last):
  File "run_mnist.py", line 234, in <module>
    main(parser.parse_args())
  File "run_mnist.py", line 136, in main
    pred = deep_mnist(args, x, train_phase)
  File "/home/v_zhizuo_zhang/projects/Harmonic_network/harmonicConvolutions/MNIST-rot/mnist_model.py", line 39, in deep_mnist
    cv2 = hn_lite.batch_norm(cv2, train_phase, name='bn1')
  File "../harmonic_network_lite.py", line 46, in batch_norm
    return h_batch_norm(x, fnc, train_phase, decay=decay, eps=eps, name=name)
  File "../harmonic_network_ops.py", line 149, in h_batch_norm
    Rb = bn(magnitude, train_phase, decay=decay, name=name)
  File "../harmonic_network_ops.py", line 176, in bn
    batch_mean, batch_var = tf.nn.moments(X, np.arange(len(Xsh)-3), name=name+'moments')
  File "/home/v_zhizuo_zhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 650, in moments
    mean = array_ops.squeeze(mean, axes)
  File "/home/v_zhizuo_zhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2281, in squeeze
    return gen_array_ops._squeeze(input, axis, name)
  File "/home/v_zhizuo_zhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3329, in _squeeze
    squeeze_dims=squeeze_dims, name=name)
  File "/home/v_zhizuo_zhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 655, in apply_op
    raise TypeError("Expected list for attr " + key)
TypeError: Expected list for attr squeeze_dims
